### ISSUE TITLE
Support Installation via Homebrew

### ISSUE THREAD

**Issue by MahatmaFatalError** [felixge/sqlbench#5]
It would be great to add this really really nice tool to [homebrew](https://brew.sh/) (the common package manager for mac) to ease the installation and update.

**Comment by felixge** [comment]
Yeah, I agree this would be nice. I've never packaged something for homebrew, so if anybody has experience with it and is willing to help, please let me know.

Otherwise I'll probably work on it at some point myself.

**Comment by chenrui333** [comment]
@MahatmaFatalError @felixge you can install with `brew install sqlbench` now. 🎉
