### ISSUE TITLE
Support installation via Chocolatey

### ISSUE THREAD

**Issue by picolino** [felixge/sqlbench#7]
[Chocolatey](https://chocolatey.org/) - is a nice windows package manager, so it will be cool if that software can be distributed by it.

I have the experience to distribute packages through chocolatey, so if you do not mind with that - I willing to create and maintain that package in future

**Comment by felixge** [comment]
Hey @picolino, sorry for the late response, this one slipped through the cracks somehow.

If you're still interested, I'd be stoked to merge Chocolatey support for this repo!

**Comment by picolino** [comment]
I've added sqlbench on the Chocolatey package manager. You can download it here:

https://chocolatey.org/packages/sqlbench

Also, @felixge, I recommend sharing the link to that package at the readme file

I will maintain that package in the nearest future and will watch for sqlbench releases to update the package accordingly

**Comment by felixge** [comment]
@picolino thank you so much for this! I just added some instructions for it to the README, PTAL: https://github.com/felixge/sqlbench/commit/6459970eb2a9bf6a65aa1dad2b68647a579a2b63
